    microservice1:
      image: 'parrajavier/appweb:latest'
      expose:
        - "8080"
    microservice2:
      image: 'parrajavier/appweb:latest'
      expose:
        - "8080"
    loadbalancer:
      image: 'dockercloud/haproxy:latest'
      links:
        - microservice1
        - microservice2
      ports:
        - '90:90'